---
output: 
    bookdown::gitbook:
        split_by: none
        split_bib: TRUE
        df_print: kable
---

```{r message=FALSE, warning=FALSE}
library(tidyverse)
```

```{r}
df <- read.table("../Model Data.csv", sep = ",", header = T)
df <- df[complete.cases(df), ]
```
 
```{r}
df %>% dim()
```
```{r}
cat_ft <- function(x) {
    case_when(x > .02 ~ "Increase",
              x < -.02 ~ "Decrease",
              TRUE ~ "No_Change")
}
df <-
    df %>%
    select(starts_with("Per_Change_T")) %>%
    mutate_all(cat_ft) %>%
    `names<-`(paste0("Class", c(1, 5, 30))) %>%
    bind_cols(df)
```

 
```{r}
fun <- function(stri) {
    as.integer(gsub(" ", "", gsub("d", "", gsub(
        "a", "", substr(stri, 1, 4)
    ))))
}

df$Delta <- fun(df$TimeDelta)
```

```{r}
library(magrittr)
df %<>% 
    mutate_at(df %>% names() %>% str_subset("Finance|General"), ~ log(.+1))
```

```{r}
df$mkvaltq <- log(df$mkvaltq)
```

 
```{r}
library(caret)
set.seed(1995)
tetr <- createDataPartition(df$Per_Change_T1, p = .75, list = F)
tr <- df[tetr, ]
te <- df[-tetr, ]
```
 
```{r}
run_model <-
    function(tr, y = "Per_Change_T1", te, x_scope = "Finance", is_combine = FALSE) {
        if (isFALSE(is_combine)) {
            is_x_scope <- FALSE
            is_combine_condition<- TRUE
        } else {
            is_x_scope <- TRUE
            is_combine_condition<- FALSE
        }
        tr_ft_list <-
            tr %>%
            names() %>%
            str_subset(x_scope, negate = is_x_scope) %>%
            str_subset("Combined", negate = is_combine_condition) %>%
            c(y, "mkvaltq", "Delta")
        tr_input <-
            tr %>%
            select(tr_ft_list)
        mod_form <- as.formula(glue::glue("{y} ~ ."))
        mod <- lm(mod_form, data = tr_input)
        beta_df <- broom::tidy(mod) %>% 
            select(term, estimate, p.value)
        # browser()
        rmse <- sqrt(mean(te[[y]] - predict(mod, newdata=te)^2))
        return(list(mod, beta_df, rmse))
    }
```
```{r}
y_list <-
    tr %>%
    names() %>%
    str_subset("Per_Change_T")
```
 
```{r results='asis'}
for (is_combine1 in c(FALSE, TRUE)) {
    for (i in y_list) {
        list(
            run_model(tr, i, te, x_scope = "Finance", is_combine = is_combine1)[2],
            run_model(tr, i, te, x_scope = "General", is_combine = is_combine1)[2]
        ) %>%
            knitr::kable() %>%
            print()
        # debugonce(run_model)
        run_model(tr, i, te, x_scope = "Finance", is_combine = is_combine1)[3] %>% paste0('RMSE(1): ', .) %>% print()
        run_model(tr, i, te, x_scope = "General", is_combine = is_combine1)[3] %>% paste0('RMSE(2): ', .) %>% print()
    }
}
```
 


